openapi: 3.0.3

info:
  title: Swagger Petstore
  description: 'This is a sample server Petstore server.  You can find out more about     Swagger
    at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For
    this sample, you can use the api key `special-key` to test the authorization     filters.'
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0

externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io

servers:
  - url: https://petstore.swagger.io/v2
  - url: http://petstore.swagger.io/v2

tags:
  - name: pet
    description: Everything about your Pets
    externalDocs:
      description: Find out more
      url: http://swagger.io
  - name: store
    description: Access to Petstore orders
  - name: user
    description: Operations about user
    externalDocs:
      description: Find out more about our store
      url: http://swagger.io

# $paths$ acts as a placeholder for all yaml definitions part of the paths folder
paths: $paths$

components:

  # $schemas$ acts as a placeholder for all yaml definitions part of the schemas folder
  schemas: $schemas$

  responses: $responses$

  parameters: $parameters$

  # examples: $examples$

  # requestBodies: $requestBodies$

  #  headers: $ headers$

  securitySchemes: $securitySchemes$

  # links: $links$

  #  callbacks: $ callbacks$

  # you may use any folder name as placeholder e.g. if you want to define hidden
  # schemas within a x-schemas folder you can use them as well.
  # $ref would then point to `#/components/x-schemas/...`
  # x-schemas: $x-schemas$
